#ifndef QTRPC2GLOBAL_H
#define QTRPC2GLOBAL_H

#ifdef QTRPC2_BUILD_LIB
#define USE_QTRPC_PRIVATE_API
#define QTRPC2_EXPORT Q_DECL_EXPORT
#else
#define QTRPC2_EXPORT Q_DECL_IMPORT
#endif

#endif // QTRPC2GLOBAL_H
